### ISSUE TITLE
Ceedling 0.32 Prerelease Error

### ISSUE THREAD

**Issue by tyler-macinnis** [deltalejo/cppcheck-ceedling-plugin#3]
When trying to current version with the prerelease of Ceedling 0.32, I'm getting the following error. I believe it is because file_system_utils doesn't exist anymore in 0.32.

```
🚧 Loaded project configuration at default location using ./project.yml
Exception raised while trying to load plugin: cppcheck

🧨 EXCEPTION: Failed to construct 'file_system_utils'
  ...caused by:
  >>> No object definition for 'file_system_utils'
```

I believe that

`@ceedling[:file_system_utils].revise_file_list( all_suppressions, in_hash[:files_cppcheck] )`

just needs to be changed to

`@ceedling[:file_path_collection_utils].revise_filelist( all_suppressions, in_hash[:files_cppcheck] )`

**EDIT:**
Also getting this error after the change above

```
🚧 Loaded project configuration at default location using ./project.yml
Exception raised while trying to load plugin: cppcheck

🧨 EXCEPTION: uninitialized constant Cppcheck::PROJECT_ROOT
Did you mean?  Projectinator
```

**Comment by deltalejo** [comment]
Hi!
I'm aware that some changes need to be done on the plugins I wrote to support Ceedling v0.32, I've already created a new branch for that some time ago, but given that the development version of Ceedling is changing a lot, I'm hesitant to address those changes until it is a bit more stable.

**Comment by deltalejo** [comment]
@tyler-macinnis 
I've fixed a few things to make the plugin works with Ceedling v0.32. Checkout [ceedling-0.32](https://github.com/deltalejo/ceedling-cppcheck-plugin/tree/ceedling-0.32) branch and let me know if that works for you.

**Comment by tyler-macinnis** [comment]
I'm currently using the most recent prerelease in a project. It still doesn't work, but I'm happy to keep testing and have made a cppcheck script in the meantime. This is the error I'm getting now.

```
ceedling cppcheck:all
🚧 Loaded project configuration at default location using ./project.yml

⏱️ Ceedling set up completed in 88 milliseconds
rake aborted!
DIY::ConstructionError: Failed to construct 'streaminator'
  ...caused by:
  >>> No object definition for 'streaminator'


Caused by:
No object definition for 'streaminator'


Caused by:
Thor::UndefinedCommandError: Could not find command "cppcheck:all".

Tasks: TOP => cppcheck:all
(See full trace by running task with --trace)
🪲 ERROR: Ceedling could not complete operations because of errors

Running Raw Tests Output Report
-------------------------------
Tests produced no extra console output.
```

**Comment by tyler-macinnis** [comment]
I think it might be best to wait to address the 0.32 changes until they are more stable as well. I think we should leave this issue open until then though just in case anyone else tries it with 0.32 and wonders why it isn't working.

**Comment by deltalejo** [comment]
It seems they are changing the logging utilities. I've made some changes to address that and now the plugin works with 0.32.0-25f0aa4.

**Comment by tyler-macinnis** [comment]
That seems to fix it! Thank you!

**Comment by deltalejo** [comment]
A few changes for Ceedling development version have been included on _main_ branch now.
I'm closing this by now but feel free to reopen if another Ceedling v0.32 issue arises.
